import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  fr: {
    // Navigation
    dashboardNav: "Tableau de bord",
    catalogue: "Catalogue",
    loans: "Emprunts",
    ai: "BookAI",
    logout: "Déconnexion",
    home: "Accueil",
    about: "À propos",
    features: "Fonctionnalités",
    contact: "Contact",

    // Landing Page
    intelligentSystem: "Système de gestion intelligent",
    manageLibraryWithAI: "Bienvenue sur",
    burkinaTech: "Burkina Institute of Technology",
    heroDescription: "La solution tout-en-un pour les écoles et entreprises. Assistant IA intégré, suivi QR en temps réel et catalogue puissant sur une plateforme élégante.",
    learnMore: "En savoir plus",
    getStarted: "Commencer",
    efficiency: "99.9% d'Efficacité",
    manualTrackingPast: "Le suivi manuel appartient au passé. Adoptez le flux numérique.",
    craftedForModern: "Conçu pour les environnements d'apprentissage modernes",
    craftedDescription: "LibraFlow est né du besoin d'un système de gestion de bibliothèque simple mais puissant. Nous combinons technologie de pointe et design centré sur l'humain.",
    realTimeSync: "Synchronisation des données en temps réel",
    crossPlatform: "Accessibilité multiplateforme",
    analytics: "Analyses et rapports détaillés",
    secureUser: "Gestion sécurisée des utilisateurs",
    powerfulFeatures: "Fonctionnalités Puissantes",
    everythingNeeded: "Tout ce dont vous avez besoin, élevé par l'IA.",
    aiLibrarian: "Bibliothécaire IA",
    aiLibrarianDesc: "Recommandations intelligentes et analyse des statistiques propulsées par les meilleurs modèles d'IA.",
    qrTracking: "Suivi par QR Code",
    qrTrackingDesc: "Gérez les emprunts et retours instantanément avec le scan et la génération de QR codes intégrés.",
    smartCatalog: "Catalogue Intelligent",
    smartCatalogDesc: "Un bel index de toutes vos ressources avec suivi de disponibilité en temps réel.",
    readyToTransform: "Prêt à transformer votre bibliothèque ?",
    joinHundreds: "Rejoignez des centaines d'institutions qui utilisent déjà LibraFlow.",
    createAccount: "Créer un compte",
    builtBy: "Développé par",

    // Dashboard
    overview: "Vue générale",
    dashboardTitle: "Tableau de bord",
    searchBooks: "Rechercher un livre...",
    history: "Historique",
    notifications: "Notifications",
    recommendedForYou: "Recommandé pour vous",
    viewAll: "Voir tout",
    noNotifications: "Aucune notification",
    yourHistory: "Votre historique",
    totalBooks: "Total livres",
    activeLoans: "En emprunt",
    available: "Disponibles",
    late: "Retards",
    mostBorrowed: "Livres les plus empruntés",
    booksByGenre: "Livres par genre",
    noData: "Aucune donnée disponible.",
    loading: "Chargement...",

    // Catalogue
    library: "Bibliothèque",
    gestion: "Gestion",
    addBook: "Ajouter un livre",
    search: "Rechercher titre, auteur...",
    allGenres: "Tous les genres",
    title: "Titre",
    author: "Auteur",
    genre: "Genre",
    copies: "Nombre d'exemplaires",
    description: "Description (optionnel)",
    cancel: "Annuler",
    add: "Ajouter",
    delete: "Supprimer",
    noBooks: "Aucun livre trouvé",
    availableCopies: "Dispo",
    status: "Statut",
    availableStatus: "Disponible",
    borrowedStatus: "Emprunté",
    pending: "En attente",
    student: "Étudiant",
    dueDate: "Date limite",
    return: "Retourner",
    newLoan: "Nouvel emprunt",
    selectBook: "Choisir un livre",
    selectUser: "ID MongoDB de l'étudiant",
    create: "Créer",
    noLoans: "Aucun emprunt",
    active: "Actif",
    returned: "Retourné",
    deleteConfirm: "Supprimer ce livre ?",
    bookDeleteSuccess: "Livre supprimé avec succès",
    borrowSuccessTitle: "Demande créée !",
    borrowSuccessDesc: "Bon d'emprunt téléchargé. Présentez-le au bibliothécaire.",
    borrowing: "Génération...",
    borrow: "📥 Emprunter",
    unavailable: "Indisponible",
    copiesLabel: "Exemplaires",

    // AI
    artificialIntelligence: "Intelligence Artificielle",
    geminiAI: "BookAI",
    poweredBy: "Assistant intelligent propulsé par Groq AI",
    chat: "Chat",
    recommendations: "Recommandations",
    summary: "Résumé",
    stats: "Analyse stats",
    askQuestion: "Posez une question sur un livre, demandez une recommandation...",
    send: "Envoyer",
    personalizedRecs: "Recommandations personnalisées",
    basedOnHistory: "Basé sur votre historique d'emprunts",
    generateRecs: "Générer mes recommandations",
    generating: "Analyse en cours...",
    bookId: "ID MongoDB du livre",
    enterBookId: "Entrez un ID de livre",
    generateSummary: "Générer le résumé",
    generatingSummary: "Génération...",
    geminiSummary: "Résumé BookAI",
    intelligentAnalysis: "Analyse intelligente",
    libraryAnalysis: "BookAI analyse l'état de votre bibliothèque",
    analyzeLibrary: "Analyser la bibliothèque",
    clickToGenerate: "Cliquez sur le bouton pour générer vos recommandations",
    aiIntro: "Bonjour ! Je suis votre assistant bibliothécaire LibraFlow propulsé par Groq AI. Posez-moi vos questions sur des livres, demandez des recommandations ou discutez de littérature !",
    clearHistory: "Effacer la conversation",
    online: "En ligne",
    clear: "Effacer",

    // Authentication
    login: "Connexion",
    register: "S'inscrire",
    email: "Email",
    password: "Mot de passe",
    signIn: "Se connecter",
    connecting: "Connexion...",
    registrationSuccess: "Inscription réussie !",
    noAccount: "Pas encore de compte ?",
    alreadyHaveAccount: "Déjà un compte ?",
    fullName: "Nom complet",
    processing: "Traitement...",
    backToHome: "Retour à l'accueil",

    // Common
    book: "Livre",
    role: "Rôle",
    librarian: "Bibliothécaire",
    user: "Utilisateur",
    scanQR: "Scanner QR",
    selectStudent: "Sélectionner un étudiant",
    confirmScan: "Scanner pour confirmer",
    returnScan: "Scanner pour retour",
    action: "Action",
  },
  en: {
    // Navigation
    dashboardNav: "Dashboard",
    catalogue: "Catalogue",
    loans: "Loans",
    ai: "BookAI",
    logout: "Logout",
    home: "Home",
    about: "About",
    features: "Features",
    contact: "Contact",

    // Landing Page
    intelligentSystem: "Intelligent Management System",
    manageLibraryWithAI: "Welcome",
    burkinaTech: "Burkina Institute of Technology",
    heroDescription: "The all-in-one solution for schools and businesses. Integrated AI assistant, real-time QR tracking and a powerful catalog on an elegant platform.",
    learnMore: "Learn More",
    getStarted: "Get Started",
    efficiency: "99.9% Efficiency",
    manualTrackingPast: "Manual library tracking is a thing of the past. Embrace the digital flow.",
    craftedForModern: "Crafted for modern learning environments",
    craftedDescription: "LibraFlow was born from the need for a simple yet powerful library management system. We combine cutting-edge technology and human-centric design.",
    realTimeSync: "Real-time data synchronization",
    crossPlatform: "Cross-platform accessibility",
    analytics: "Detailed analytics and reporting",
    secureUser: "Secure user management",
    powerfulFeatures: "Powerful Features",
    everythingNeeded: "Everything you need, elevated by AI.",
    aiLibrarian: "AI Librarian",
    aiLibrarianDesc: "Intelligent recommendations and statistics analysis powered by top-tier AI models.",
    qrTracking: "QR Tracking",
    qrTrackingDesc: "Manage loans and returns instantly with built-in QR code scanning and generation.",
    smartCatalog: "Smart Catalog",
    smartCatalogDesc: "A beautiful index of all your resources with real-time availability tracking.",
    readyToTransform: "Ready to transform your library?",
    joinHundreds: "Join hundreds of institutions already using LibraFlow.",
    createAccount: "Create Account",
    builtBy: "Built by",

    // Dashboard
    overview: "Overview",
    dashboardTitle: "Dashboard",
    searchBooks: "Search for a book...",
    history: "History",
    notifications: "Notifications",
    recommendedForYou: "Recommended for you",
    viewAll: "View all",
    noNotifications: "No notifications",
    yourHistory: "Your history",
    totalBooks: "Total books",
    activeLoans: "Active Loans",
    available: "Available",
    late: "Late",
    mostBorrowed: "Most Borrowed Books",
    booksByGenre: "Books by Genre",
    noData: "No data available.",
    loading: "Loading...",

    // Catalogue
    library: "Library",
    gestion: "Management",
    addBook: "Add Book",
    search: "Search title, author...",
    allGenres: "All Genres",
    title: "Title",
    author: "Author",
    genre: "Genre",
    copies: "Number of copies",
    description: "Description (optional)",
    cancel: "Cancel",
    add: "Add",
    delete: "Delete",
    noBooks: "No books found",
    availableCopies: "Available",
    status: "Status",
    availableStatus: "Available",
    borrowedStatus: "Borrowed",
    pending: "Pending",
    student: "Student",
    dueDate: "Due Date",
    return: "Return",
    newLoan: "New Loan",
    selectBook: "Select a book",
    selectUser: "Student MongoDB ID",
    create: "Create",
    noLoans: "No loans",
    active: "Active",
    returned: "Returned",
    deleteConfirm: "Delete this book?",
    bookDeleteSuccess: "Book successfully deleted",
    borrowSuccessTitle: "Request created!",
    borrowSuccessDesc: "Loan voucher downloaded. Present it to the librarian.",
    borrowing: "Generating...",
    borrow: "📥 Borrow",
    unavailable: "Unavailable",
    copiesLabel: "Copies",

    // AI
    artificialIntelligence: "Artificial Intelligence",
    geminiAI: "BookAI",
    poweredBy: "Smart assistant powered by Groq AI",
    chat: "Chat",
    recommendations: "Recommendations",
    summary: "Summary",
    stats: "Stats Analysis",
    askQuestion: "Ask a question about a book, request a recommendation...",
    send: "Send",
    personalizedRecs: "Personalized Recommendations",
    basedOnHistory: "Based on your borrowing history",
    generateRecs: "Generate My Recommendations",
    generating: "Analyzing...",
    bookId: "Book MongoDB ID",
    enterBookId: "Enter a book ID",
    generateSummary: "Generate Summary",
    generatingSummary: "Generating...",
    geminiSummary: "BookAI Summary",
    intelligentAnalysis: "Intelligent Analysis",
    libraryAnalysis: "BookAI analyzes your library status",
    analyzeLibrary: "Analyze Library",
    clickToGenerate: "Click the button to generate your recommendations",
    aiIntro: "Hello! I am your LibraFlow librarian assistant powered by Groq AI. Ask me your questions about books, request recommendations or discuss literature!",
    clearHistory: "Clear conversation",
    online: "Online",
    clear: "Clear",

    // Authentication
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    connecting: "Signing in...",
    registrationSuccess: "Registration successful!",
    noAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    fullName: "Full Name",
    processing: "Processing...",
    backToHome: "Back to Home",

    // Common
    book: "Book",
    role: "Role",
    librarian: "Librarian",
    user: "User",
    scanQR: "Scan QR",
    selectStudent: "Select a student",
    confirmScan: "Scan to confirm",
    returnScan: "Scan for return",
    action: "Action",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("fr");

  // Load saved language preference
  useEffect(() => {
    const saved = localStorage.getItem("libraflow-lang");
    if (saved) setLang(saved);
  }, []);

  // Save language preference
  useEffect(() => {
    localStorage.setItem("libraflow-lang", lang);
  }, [lang]);

  const t = (key) => translations[lang][key] || key;
  const toggleLang = () => setLang((prev) => (prev === "fr" ? "en" : "fr"));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context)
    throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
